src/main/java/tconstruct/armor/PlayerAbilityHelper.java, src/main/java/tconstruct/util/config/PHConstruct.java
Disallow Traveller's Belt ability to swap inventories for certain dimension ID's
=> Added forbidden dimension config

src/main/java/tconstruct/armor/player/ArmorExtended.java
=> SoulBound support for additional TC slots

src/main/java/tconstruct/items/tools/LumberAxe.java
Should fix lumberaxe leveling and modifier applications
=> Whoops, left this out.

src/main/java/tconstruct/TConstruct.java
Let it load before GalacticraftCore
=> Changed Dependencies to prevent missing "tile.unlitTorch_Stone" errors.

src/main/java/tconstruct/items/tools/LumberAxe.java
I can't reproduce locally so I can't test if this works.
=> Maybe fix lumber axe error

src/main/java/tconstruct/util/network/AccessoryInventoryPacket.java, src/main/java/tconstruct/util/network/PatternTablePacket.java, src/main/java/tconstruct/util/network/SignDataPacket.java, src/main/java/tconstruct/util/network/SmelteryPacket.java, src/main/java/tconstruct/util/network/ToolStationPacket.java
Fix possible packet hacking [REDACTED]
=> Fix possible packet hacking [REDACTED]

src/main/java/tconstruct/armor/ArmorAbilities.java, src/main/java/tconstruct/armor/items/TravelWings.java, src/main/java/tconstruct/armor/player/ArmorExtended.java, src/main/java/tconstruct/armor/player/KnapsackInventory.java, src/main/java/tconstruct/armor/player/TPlayerStats.java, src/main/java/tconstruct/items/tools/Battleaxe.java, src/main/java/tconstruct/library/tools/AbilityHelper.java, src/main/java/tconstruct/library/weaponry/ProjectileWeapon.java, src/main/java/tconstruct/mechworks/blocks/BlockLandmine.java, src/main/java/tconstruct/smeltery/logic/SmelteryLogic.java, src/main/java/tconstruct/tools/TinkerToolEvents.java, src/main/java/tconstruct/tools/inventory/CraftingStationContainer.java, src/main/java/tconstruct/tools/inventory/PartCrafterChestContainer.java, src/main/java/tconstruct/tools/logic/CraftingStationLogic.java, src/main/java/tconstruct/tools/logic/StencilTableLogic.java, src/main/java/tconstruct/tools/logic/ToolStationLogic.java
Fixed a lot of NPE's and few duplication glitches (cherry-picked from other fork)
=> Fixed a lot of NPE's and few duplication glitches

build.properties, src/main/java/tconstruct/plugins/nei/RecipeHandlerBase.java
Fix mouse position calculation for fluid tanks in NEI handlers.
* Fixes https://github.com/GTNewHorizons/NotEnoughItems/issues/102
=> Fix NEI mouse position calculation

src/main/java/tconstruct/tools/gui/StencilTableGui.java
Fix: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9057
=> Stencil Table and NEI overlap

src/main/java/tconstruct/tools/gui/CraftingStationGui.java
~~Looks uglier, but you can click on things.~~
Resort to hacks for mouseClick.
stupid GUIs
=> Fix clicking on inventory slots

build.gradle
Signed-off-by: Glease <4586901+Glease@users.noreply.github.com>
=> update buildscipt to fix mantle transitive dep

src/main/java/tconstruct/library/crafting/CastingRecipe.java, src/main/java/tconstruct/smeltery/TinkerSmeltery.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6971
=> Add a way to ignore NBT in casting recipes

src/main/java/tconstruct/tools/gui/CraftingStationGui.java
issue: https://github.com/GTNewHorizons/NotEnoughItems/issues/223
=> Fix Tinkers Crafting Tables Height

build.gradle, src/main/java/tconstruct/smeltery/blocks/LavaTankBlock.java, src/main/java/tconstruct/smeltery/itemblocks/LavaTankItemBlock.java, src/main/java/tconstruct/smeltery/logic/LavaTankLogic.java
=> Implement IFluidContainerItem for LavaTankItemBlock

build.gradle, dependencies.gradle, src/main/java/tconstruct/tools/gui/ChestSlot.java, src/main/java/tconstruct/tools/gui/CraftingStationGui.java, src/main/java/tconstruct/tools/inventory/CraftingStationContainer.java
The default implementation just returns true, this makes it re-use the logic implemented by the inventory used.
=> Make crafting stations slots use ISidedInventory/IInventory validation logic

build.gradle, dependencies.gradle, src/main/java/tconstruct/tools/gui/CraftingStationGui.java
Fixes slots moving outside the bounds of the gui window when scrolling
=> Fix broken scrolling of large inventories in the crafting station

src/main/java/tconstruct/library/weaponry/BowBaseAmmo.java
Hopefully address https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10910
=> Add null check

src/main/java/tconstruct/client/ArmorControls.java
tested and works in dev of course
=> fix bug where it triggers key actions when you have keybinds set to none

src/main/java/tconstruct/client/ArmorControls.java, src/main/java/tconstruct/plugins/nei/BeltToggleFromGuiInputHandler.java
if you have the traveller's belt NEI hotkey un-binded, the hotbar swap toggles when typing certain keys in the NEI GUI, it even happens when typing in the search bar, for example on my keyboard it triggers when typing ">".
This PR fixes that
=> stop toggling the traveller's belt hotbar swap in the NEI GUI

src/main/java/tconstruct/library/tools/AOEHarvestTool.java
=> Backport: Only break one block when sneaking

src/main/java/tconstruct/smeltery/TinkerSmeltery.java
=> Readd recipe for reinforcement

src/main/java/tconstruct/TConstruct.java, src/main/java/tconstruct/library/tools/AbilityHelper.java, src/main/java/tconstruct/tools/entity/DaggerEntity.java, src/main/java/tconstruct/util/config/PHConstruct.java
commit that broke it : https://github.com/GTNewHorizons/TinkersConstruct/pull/73
closes the ticket : https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12567
=> Revert signature changes of public methods that caused crashes

build.gradle, dependencies.gradle
=> Update BS and Dep of Mantle

src/main/java/tconstruct/smeltery/TinkerSmeltery.java
Addressing this issue:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9730
=> Remove smeltery tracks melting recipe

build.gradle, src/main/java/tconstruct/items/tools/LumberAxe.java
Here's the issue: (break speed is reduced for easier reproduction)
https://github.com/GTNewHorizons/TinkersConstruct/assets/40035906/363300d5-2a98-4fa0-8db1-fcee9c7ead97
=> Fix lumberaxe chain break not validating held item

src/main/java/tconstruct/library/tools/HarvestTool.java, src/main/java/tconstruct/tools/TinkerTools.java
(feature can waiting)
Now tinker's tools can place cobblestone with ztones ofanix by right click
=> tinker's + ofanix

src/main/java/tconstruct/gadgets/item/ItemSlimeBoots.java
* onItemRightClick() endlessly created fake boots
=> fix slime boots

dependencies.gradle, src/main/java/tconstruct/library/weaponry/AmmoWeapon.java, src/main/java/tconstruct/library/weaponry/BowBaseAmmo.java, src/main/java/tconstruct/library/weaponry/ProjectileWeapon.java, src/main/java/tconstruct/weaponry/weapons/Crossbow.java
https://github.com/GTNewHorizons/Battlegear2/pull/19
=> use updated battlegear2 api

README.md, src/main/resources/assets/tinker/lang/en_US.lang
Partially fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14161
=> add name for crystal entity (which seems to be a creeper?

build.gradle, src/main/java/tconstruct/world/TinkerWorld.java
more work on https://github.com/GTNewHorizons/Dupes-Exploits-GTNH/issues/111
only changes anything if iguanatweaks is detected
=> Obsidian harvestlevel fix

src/main/java/tconstruct/tools/logic/CraftingStationLogic.java
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15206
=> Function `P` crash if crafting station without chest

src/main/java/tconstruct/client/pages/ToolPage.java
Required for my plan to use lang files to make Tinker's Construct books loaded from dreamcraft support i18n.
=> Translate all tool parts

src/main/java/tconstruct/tools/logic/ToolForgeLogic.java, src/main/java/tconstruct/tools/logic/ToolStationLogic.java
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15818
=> Send tool localization name to server

src/main/java/tconstruct/plugins/nei/CraftingStationStackPositioner.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15952
=> Fix NEI recipe preview in grid

src/main/java/tconstruct/util/config/PHConstruct.java, src/main/java/tconstruct/world/items/OreBerries.java
As requested by @brandyyn, this PR adds a config for https://github.com/GTNewHorizons/TinkersConstruct/pull/114
=> Add config for batch essence berry consumption

src/main/java/tconstruct/library/crafting/AlloyMix.java, src/main/java/tconstruct/library/crafting/Smeltery.java, src/main/java/tconstruct/smeltery/logic/SmelteryLogic.java, src/main/java/tconstruct/smeltery/model/SmelteryRender.java
Fixes https://github.com/GTNewHorizons/Angelica/issues/543
=> Convert to threadsafe molten metal list

src/main/java/tconstruct/items/tools/LumberAxe.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17457
Lumber axe can now chop down the entire tree with branches, such as large oak tree, greatwood tree and sacred oak tree. not including redwood tree
=> Expand tree detecting and chopping range of lumber axe

src/main/java/tconstruct/library/crafting/CastingRecipe.java
=> Fix NPE making gold casts while they are disabled

src/main/java/tconstruct/world/TinkerWorld.java
#137 
Orebushes' ore dict tags aren't fixed in the previous pull request.
=> Orebush oredict tag fix

src/main/java/tconstruct/library/weaponry/AmmoWeapon.java, src/main/java/tconstruct/library/weaponry/ProjectileWeapon.java, src/main/java/tconstruct/weaponry/weapons/Crossbow.java
makes the reinforced modifier work on ammo like it does in newer versions
=> Ammo reinforced modifier support

src/main/java/tconstruct/library/crafting/AlloyMix.java
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18541#issuecomment-2563715632
=> fix crash in AlloyMix.java

src/main/java/tconstruct/blocks/slime/SlimeFluid.java
Blocked a terrible flow-based slime farm.
fix: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18543
related: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/1519#issuecomment-310722159
=> Fix blue slime spawn 

src/main/java/tconstruct/library/crafting/ToolBuilder.java, src/main/java/tconstruct/world/entity/KingBlueSlime.java, src/main/resources/assets/tinker/lang/en_US.lang, src/main/resources/assets/tinker/lang/zh_CN.lang
Fixes https://github.com/GTNewHorizons/TinkersConstruct/issues/150
Tested to be working as intended.
Other languages like Japanese might need their own format specified in lang file too.
=> Improve localization for tools

src/main/java/tconstruct/plugins/nei/RecipeHandlerDryingRack.java, src/main/resources/assets/tinker/lang/en_US.lang
prev PR: https://github.com/GTNewHorizons/TinkersConstruct/pull/156
=> Change Rank Duration Localization key

src/main/java/tconstruct/armor/TinkerArmor.java, src/main/java/tconstruct/gadgets/TinkerGadgets.java, src/main/java/tconstruct/mechworks/TinkerMechworks.java, src/main/java/tconstruct/plugins/gears/TinkerGears.java, src/main/java/tconstruct/plugins/ic2/TinkerIC2.java, src/main/java/tconstruct/plugins/te4/TinkerTE4.java, src/main/java/tconstruct/smeltery/TinkerSmeltery.java, src/main/java/tconstruct/tools/TinkerTools.java, src/main/java/tconstruct/util/config/PHConstruct.java, src/main/java/tconstruct/weaponry/TinkerWeaponry.java, src/main/java/tconstruct/world/TinkerWorld.java
It builds, but I hope spotless java doesn't fuck me over
=> Add "Disable All Recipes" config option

src/main/java/tconstruct/plugins/ic2/Ic2CropHarvestHandler.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19884
=> Add check for getCrop() being null

src/main/resources/assets/tinker/lang/ja_JP.lang
I'm really farming these PRs now, aren't I?
=> Add missing equals sign.

src/main/java/tconstruct/plugins/nei/CraftingStationOverlayHandler.java
=> Add Autocrafting to Crafting Station
