build.gradle, build.properties, src/main/java/tconstruct/items/tools/LumberAxe.java, src/main/java/tconstruct/library/tools/HarvestTool.java
Backported lumberaxe tree chop task from master; should fix issues with forestry trees only dropping one wood
Fixes https://github.com/GTNewHorizons/NewHorizons/issues/2276
=> Backport lumberaxe tree chop task from master

src/main/java/tconstruct/library/tools/HarvestTool.java
Guards against: 
```java
java.lang.NullPointerException: Exception in server tick loop
at tconstruct.library.tools.HarvestTool.breakExtraBlock(HarvestTool.java:292)
at tconstruct.items.tools.LumberAxe$TreeChopTask.onWorldTick(LumberAxe.java:256)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_1378_TreeChopTask_onWorldTick_WorldTickEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:273)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:957)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
at …
```
=> Add a null check in case there is no current equipped item

src/api/java/mods/battlegear2/api/core/InventoryPlayerBattle.java, src/api/java/mods/battlegear2/api/core/InventorySlotType.java, src/api/java/mods/battlegear2/api/core/UnhandledInventoryItemEvent.java, src/main/java/tconstruct/library/weaponry/AmmoItem.java, src/main/java/tconstruct/library/weaponry/AmmoWeapon.java, src/main/java/tconstruct/library/weaponry/BowBaseAmmo.java, src/main/java/tconstruct/library/weaponry/ProjectileWeapon.java, src/main/java/tconstruct/weaponry/weapons/Crossbow.java
Added ability to equip Tinker's bows/crossbow/throwables to Battlegear slots.  Bows will only look in the same offhand, or the main inventory for ammo.
https://github.com/GTNewHorizons/NewHorizons/issues/2491
=> Tinkers bows in Battlegear slots

resources/assets/tinker/lang/en_US.lang, src/main/java/tconstruct/client/ArmorControls.java, src/main/java/tconstruct/plugins/nei/BeltToggleFromGuiInputHandler.java, src/main/java/tconstruct/plugins/nei/NEITConstructConfig.java
This adds support for swapping toolbars in GUIs. It uses a separate keybinding (due to how NEI works) that is currently not set by default, so one must explicitly bind it in the NEI options for now. It's a client side only fix.
=> Add support for swapping belt toolbars in inventory GUIs.

build.properties, src/main/java/tconstruct/library/TConstructRegistry.java
@Prometheus0000, this is the follow-on PR for:
* https://github.com/GTNewHorizons/TinkersGregworks/pull/6
This PR fixes the super-bugged item issue that I mentioned in the PR above. With both of these PRs, I think deleting materials works okay, though there is still some weirdness. We could also use some other material instead of `Wood` as a fallback, though tools keep their old stats so it may not make much difference.
I tried testing with deleting Oureclase with a minimal testing set of mods, and here's what I saw happen:
Tinker's tools using the bugged material have those parts replaced with "Wood", but they still retain the same stats as the deleted material used to have. The tool seems to work just fine, though it has a tooltip saying that it should be placed in a crafting grid to …
=> Add a fall back if we try to look up a missing material

src/main/java/tconstruct/smeltery/gui/SmelteryGui.java
1. Fix seared stone blocks displayed amount. We use 360mb per block, not 144mb per block. We also have no casting recipe for seared bricks (nor do we allow seared stone fluid to seared brick conversion)
2. Added press LSHIFT to show exact fluid amount instead of blocks or ingots.
=> Improve smeltry GUI tooltip

src/main/java/tconstruct/smeltery/logic/SmelteryLogic.java
so that you don't need a freaking remote comparator to read the fluid amount, and let's just keep that regen enderman contributing to our cause...
=> actively update drain comparator output 

src/main/java/tconstruct/gadgets/TinkerGadgets.java, src/main/java/tconstruct/gadgets/item/ItemSlimeBoots.java, src/main/java/tconstruct/library/SlimeBounceHandler.java
* Use vec3 instead of Vector3d which isn't found on the server
* set entity.motionXYZ manually, as setVelocity is ClientOnly
* Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11140
=> Fix slimeboots & slimesling

src/main/java/tconstruct/TConstruct.java, src/main/java/tconstruct/armor/player/ArmorExtended.java, src/main/java/tconstruct/library/tools/AbilityHelper.java, src/main/java/tconstruct/library/tools/ToolCore.java, src/main/java/tconstruct/tools/entity/DaggerEntity.java, src/main/java/tconstruct/tools/entity/FancyEntityItem.java, src/main/java/tconstruct/util/config/PHConstruct.java, src/main/java/tconstruct/weaponry/weapons/Javelin.java
adds the config options from the [tinkered constructor](https://www.curseforge.com/minecraft/mc-mods/tinkered-constructor) fork of tinkers construct, including.
- dropping heart canisters on death
- disabling tinker tools being indestructible
- changing the global item despawn time
- changing the tinkers dagger damage output with a multiplier
all config options are set to function like vanilla by default.
=> adding the config options from the tinkered constructor fork

build.gradle, src/main/java/tconstruct/gadgets/item/ItemSlimeBoots.java, src/main/java/tconstruct/gadgets/item/ItemSlimeSling.java, src/main/java/tconstruct/tools/items/CreativeModifier.java, src/main/resources/assets/tinker/lang/en_US.lang, src/main/resources/assets/tinker/lang/ru_RU.lang
About "gadgets.slime_boots.tooltip3= to stop bouncing."...
It have to be non hard-coded space after "=", because in the russian language (and possibly in some others) there should be a comma after the button name. Example: "Зажмите shift, чтобы увидеть доп. информацию"
=> Replace some hard-coded tooltips with translatable text

src/main/java/tconstruct/smeltery/logic/CastingBlockLogic.java, src/main/java/tconstruct/smeltery/logic/SmelteryLogic.java
Smeltery structure check fills internal arrayList of drains and lava tanks
without clearing drains beforehand they get filled forever and cause lag due to thousands of block updates
this pr fixes that(and also includes mitch's old unpushed changes)
=> fix smeltery tps lag by clearing drain array before structure check

README.md
According to @eigenraven, the workspace step is no longer necessary, although it is still recommended to build the project before importing it to one's IDE.
=> Readme: remove the workspace step

src/main/java/tconstruct/smeltery/logic/SmelteryDrainLogic.java, src/main/java/tconstruct/smeltery/logic/SmelteryLogic.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12867
markDirty gets called when you insert items in the smeltery. You could accelerate smelting time by spam inputting items using mouse wheel, since markDirty also updated the smeltery for no reason.
Also fixes drain comparator output being 0 even with fluid inside smeltery. Small values used to be truncated and are now rounded up instead.
=> fix smeltery acceleration and comparator output

src/main/java/tconstruct/tools/gui/StencilTableGui.java, src/main/java/tconstruct/weaponry/WeaponryClientProxy.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13542
added guards before setActiveButton and setSelectedPattern if item is not a valid stencil
Also noticed tinkers weaponry buttons were added in wrong order which made setActiveButton set the wrong button
=> fix crash when opening stencil table with cast

build.gradle, src/main/java/tconstruct/smeltery/TinkerSmeltery.java
this mod is supported 'actively' which means also outside the pack. please dont just remove recipes because we dont want them in GTNH.
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9730
=> Fix tracks properly

src/main/java/tconstruct/library/armor/ArmorCore.java
This is because it was given the `break` tag while erroneously setting all its damage to 0.
=> Fixes broken TiC Armor not being repairable

src/main/java/tconstruct/armor/ArmorProxyClient.java, src/main/java/tconstruct/client/HealthBarRenderer.java
Tinkers constructs completely overwrites the health bar rendering and there were multiple bugs with it. Notably it was drawing all of the hearts that your character has on top of each other even though you can only see the 10 hearts at the very top, costing performance for nothing.
In this pr I :
- add some code that has been forgotten when copying and overriding the vanilla renderHealth method
- create dedicated class HealthBarRenderer extending Gui to stop copy-pasting certain vanilla methods
- fix renegeration hearts moving when the game is paused
- only bind tinkers hearts textures if it's actually going to draw tinkers' hearts (helth above 20)
- stop drawing vanilla hearts when they are hidden by tinkers' heart being drawn on top
- fix tinker's half heart not moving with regeneration …
=> Fix health bar renderer

src/main/java/tconstruct/client/HealthBarRenderer.java
weakens EventPriority (raised in #97) of HealthBarRenderer to High to allow DualHotbar to shift the renderer up again
[before](https://github.com/GTNewHorizons/TinkersConstruct/assets/27380203/f1fd3409-0160-4309-be86-af26a2759762) & [after](https://github.com/GTNewHorizons/TinkersConstruct/assets/27380203/43756be2-9a7e-40ba-ae9e-a83aa304f84f)
=> fix health bar not being shifted up by DualHotbar

dependencies.gradle, src/main/java/tconstruct/plugins/nei/NEITConstructBookmarkContainerHandler.java, src/main/java/tconstruct/plugins/nei/NEITConstructConfig.java
Please can someone test this feature with an unbiased view? Add something like iron chests to your test env so that the crafting station has a scrollbar.
The code sadly uses some magic numbers, I couldn't think of any other simple way to do it.
See https://github.com/GTNewHorizons/NotEnoughItems/pull/410 for what exactly it does. This time it also supports crafting stations.
=> NEI bookmark pulling

src/main/java/tconstruct/smeltery/blocks/LavaTankBlock.java
This PR is intended to make the Seared Tank behave like any other fluid container block when it comes to interacting with fluid container items when right-clicked.
- Clay Buckets don't splash water clientside when filling the tank.
- Bottles, Cells and other non-Bucket containers do not get consumed when filling the tank and are instead replaced by their empty container.
- Any container which can fill the tank can now drain it, this includes Clay Buckets, Cells and Bottles.
- There is a `public static ItemStack consumeItem(ItemStack stack)` method on LavaTankBlock which now isn't used anywhere, is copy-pasted from `buildcraft.core.lib.inventory.InvUtils` and probably wasn't meant to be public. I've kept it to avoid a public API change. I'd rather remove it or at least mark it as …
=> Seared Tank QOL

src/main/java/tconstruct/client/TProxyClient.java, src/main/java/tconstruct/tools/items/Manual.java, src/main/java/tconstruct/tools/items/ManualInfo.java
Don't load any manuals from Tinker's Construct if dreamcraft is loaded.
This PR needs to be merged for https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/797 to fully take effect.
=> Delegate manuals to dreamcraft

src/main/java/tconstruct/world/items/OreBerries.java
As the title says, this PR aims to make the use of essence berries less annoying by allowing the player to consume whole stacks of them at once when sneaking. 
When a stack of essence berries is consumed, it also doesn't spawn experience orb entities in word but rather adds the experience to the player directly to avoid unnecessary entity spam.
When the player is not sneaking, the berries behave as usual (one berry consumed per click, xp orbs spawn).
https://github.com/GTNewHorizons/TinkersConstruct/assets/93287602/e5789808-ffa2-416f-88d4-e0216700ce61
=> Allow stacks of essence berries to be consumed at once

README.md, src/main/java/tconstruct/TConstruct.java, src/main/java/tconstruct/items/tools/Excavator.java, src/main/java/tconstruct/items/tools/Hammer.java, src/main/java/tconstruct/items/tools/LumberAxe.java, src/main/java/tconstruct/library/tools/AOEHarvestTool.java, src/main/java/tconstruct/library/util/AoEExclusionList.java
This feature would enhance control over tool behavior and can prevent accidental destruction of important blocks, think accidentally breaking a wall of chests with a lumber axe, or destroying your Smeltery Controller when breaking Seared brick blocks.
Key Changes:
Created new class under tconstruct.library.util to handle loading and checking exclusions for AoE tool effects.
Lists are determined by a config (preferably pre-set with desired defaults).
Lists are separated into exclusions lists for individual tools, so a separate blacklist can exist for the hammer, separate from the excavator or lumberaxe.
Updated the AOEHarvestTool class to add a check before breaking blocks via AoE, of course keeps original functionality.
Did the whole gauntlet of gradle tests, no issues. Of course i may …
=> Implementation of AoE Blacklist for Tinker's Construct Tools

src/main/java/tconstruct/blocks/slime/SlimeGel.java
Also it seems lumbers didnt chop the whole slime tree down. This pr also fix it.
=> Fix slime leaves decay when still connected to slime block

src/main/java/tconstruct/tools/inventory/CraftingStationContainer.java
This PR is just a quality of life change. When shift-clicking weapons, tools and other tinker stuff into the crafting station, they will now move into the center slot, if possible. If not, the normal transfer logic continues.
Using tinker tools inside the crafting station is only really done to apply modifiers to them. Before this change, the items would always end up in the bottom-right slot.
=> feat: move tinker tools and weapons to center of crafting station

src/main/java/tconstruct/armor/ArmorProxyClient.java, src/main/java/tconstruct/armor/player/ArmorExtended.java, src/main/java/tconstruct/util/config/PHConstruct.java
The Traveller's Belt and Glove can now be hidden from rendering on the body through a config option, or they can be enchanted with Translucency I or II from Witching Gadgets and that will work as expected too.  Unfortunately I couldn't figure out how to get the infusion itself to detect the recipe properly with either the glove or the belt, so in order to apply the enchantment you will need to get it onto a book first and apply it with an anvil.
=> Allow hiding of Traveller's Gear accessories (gloves and belt) through config option and Translucency enchant

dependencies.gradle, settings.gradle, src/main/java/tconstruct/util/config/PHConstruct.java
Just changes the default to the old value. Doesn't affect GTNH as it is already set there explicitly:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/10628584857b5a973d4b45a446a87dcd7746754e/config/TinkersConstruct.cfg#L36
Fixes #128
=> Revert default config for option "Remove Gold Cast Recipes"

src/main/java/tconstruct/util/config/PHConstruct.java
As requested by @Dream-Master and @mitchej123
Set the default value of the "Remove Gold Cast Recipes" option based on whether we are in GTNH. I didn't see the value in adding the GTNH check everywhere the `PHConstruct#removeGoldCastRecipes` field is read.
Follow-up for #130.
=> Explicit GTNH check for gold cast removal config

src/main/java/tconstruct/world/itemblocks/WoolSlab1Item.java, src/main/java/tconstruct/world/itemblocks/WoolSlab2Item.java
There seem to be something odd with the way wool slabs's meta is handled:
- There's `WoolSlab1` which goes from White to gray, and `WoolSlab2` which goes from light gray to black.
- For `WoolSlab1` and `WoolSlab2,` the bottom slab goes from meta 1 -> 7 and top slab from 7 -> 15 (which makes it weird with color meta standard in minecraft).
This commit only fixes the unlocalized name to work according to this logic, without affecting any existing world save.
Fix GTNewHorizons/GT-New-Horizons-Modpack#17826
=> Fix unlocalized name of Wool Slabs

src/main/java/tconstruct/world/TinkerWorld.java
Essence Berry OreDict tags were wrongly applied to Gold Berries.
Fixes https://github.com/GTNewHorizons/TinkersConstruct/issues/137
=> Fix Essence Berry OreDict tags

src/main/resources/assets/tinker/lang/en_US.lang
This adds some missing localizations for unlocalized names returned by the ItemStack-insensitive version of `Item.getUnlocalizedName()`.
Relevant for the Item/Block stats introduced in https://github.com/GTNewHorizons/Hodgepodge/pull/398.
=> Add Localizations

src/main/java/tconstruct/world/gen/TBaseWorldGenerator.java
- fixes worldgen in custom dimensions
=> check against `isSurfaceWorld()` instead of `dimensionId == 0`

src/main/java/tconstruct/library/TConstructRegistry.java, src/main/java/tconstruct/smeltery/TinkerSmeltery.java, src/main/java/tconstruct/util/config/PHConstruct.java, src/main/java/tconstruct/weaponry/TinkerWeaponry.java
Adds a config to exchange AluminumBrass for another FluidType register with TiCo during the pre-init phase.
Needed to use GT brass instead of TiCo AluminumBrass in the modpack. I plan to register the FluidType in Dreamcraft.
Also includes some code cleanup which helped me make sure I didn't miss a recipe.
```
crossmodinteractions {
S:"Metal cast FluidType"=Aluminum
}
```
=> Allow overriding AluminumBrass as the metal pattern material

src/main/java/tconstruct/smeltery/gui/SmelteryGui.java
Also a small code cleanup. I changed some method signatures after making sure they were used nowhere else in the pack.
=> Don't display "Fuel" instead of the liquid's name when holding shift in the Smeltery UI

src/main/java/tconstruct/tools/entity/FancyEntityItem.java
For some reason this was set to 20 (ticks) before, which is double the normal for items. Set it to 10 to match usual behavior
=> Set tinker tool pickup delay to standard 10 ticks

dependencies.gradle, src/main/java/tconstruct/TConstruct.java, src/main/java/tconstruct/api/harvesting/CropHarvestHandler.java, src/main/java/tconstruct/api/harvesting/CropHarvestHandlers.java, src/main/java/tconstruct/api/harvesting/VanillaCropsHarvestHandler.java, src/main/java/tconstruct/items/tools/Scythe.java, src/main/java/tconstruct/plugins/ic2/Ic2CropHarvestHandler.java, src/main/java/tconstruct/plugins/ic2/TinkerIC2.java, src/main/java/tconstruct/plugins/natura/NaturaCropHarvestHandler.java, src/main/java/tconstruct/plugins/natura/TinkerNatura.java, src/main/java/tconstruct/util/config/PHConstruct.java
This PR was started to bring the crop harvesting ability of the Gregtech Sense back into the pack after that item was removed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/3203.
To keep things simple, at this time the scythe has the exact same 5x5x5 range that the Sense had, even though it's normal left click destructive harvest ability is still 3x3. I do not have a sensible plan for allowing you to reduce or increase that range without risking enormous scope creep, but suggestions are welcome.
While I was at it, I extended the crop harvesting support to Vanilla, Harvestcraft and Natura crops, as well as the IC2 crops the Sense originally supported.
Note: It is difficult to see in the video but this does use tool durability, though not very much. This could be scaled as desired …
=> Allow the Scythe to harvest crops in an AOE

src/main/java/tconstruct/world/TinkerWorldEvents.java
Cancel the bone meal event if slimeSapling.boneFertilize fails (happens if the player is not in creative mode).
This prevents wasting bone meal that would have no effect. The player will still swing the bone meal, but nothing else will happen.
=> Prevent wasting bone meal on slimy saplings in survival.

src/main/java/tconstruct/smeltery/logic/SmelteryLogic.java
This code previously damaged entities (and voided the gained fluids) in the original bounds of a smeltery that was made invalid but still had liquid in its controller.
Before:
https://github.com/user-attachments/assets/e2ada461-30b7-402e-8a5a-cb43e5fe466c
After:
https://github.com/user-attachments/assets/cf3f6d00-62b9-40ed-a97c-af2e2e0032f7
Also simplify the empty check and use a pattern variable in this method.
=> Only check for entities to damage if the structure is valid

src/main/java/tconstruct/compat/Battlegear2Compat.java, src/main/java/tconstruct/library/weaponry/BowBaseAmmo.java, src/main/java/tconstruct/weaponry/weapons/Crossbow.java
Battlegear 2 for Backhand has `IBattlePlayer` but not `IInventoryPlayerBattle` so that latter class needs to be placed somewhere where it won't be class loaded. This works because `battlegear2$isBattlemode` is always false for the Backhand edition of BG2.
=> Battlegear 2 for Backhand compat

src/main/java/tconstruct/smeltery/logic/CastingBlockLogic.java, src/main/java/tconstruct/smeltery/logic/FaucetLogic.java, src/main/java/tconstruct/smeltery/model/CastingBasinSpecialRender.java, src/main/java/tconstruct/smeltery/model/CastingTableSpecialRenderer.java
Casting Tables and Basins can now face all four cardinal directions rather than just one (repeaters for block facing reference):
The direction chosen is based on the direction the player is facing when placing the block (the value is saved to the TE's NBT).
Also made a fix for the logic used when placing Seared Faucets while looking at the top or bottom of a block. It now defers to the other method that uses the player's rotation if the player doesn't place it against the side of a block.
=> Casting Table/Basin Facing Directions

dependencies.gradle, src/main/java/tconstruct/TConstruct.java, src/main/java/tconstruct/compat/LoadedMods.java, src/main/java/tconstruct/library/tools/ToolCore.java, src/main/java/tconstruct/library/weaponry/AmmoItem.java, src/main/java/tconstruct/library/weaponry/BowBaseAmmo.java, src/main/java/tconstruct/library/weaponry/ProjectileWeapon.java, src/main/java/tconstruct/weaponry/ammo/ArrowAmmo.java, src/main/java/tconstruct/weaponry/ammo/BoltAmmo.java, src/main/java/tconstruct/weaponry/weapons/Crossbow.java, src/main/java/tconstruct/weaponry/weapons/LongBow.java, src/main/java/tconstruct/weaponry/weapons/ShortBow.java, src/main/resources/assets/tinker/lang/en_US.lang
Since the Battlegear slots were removed, the inventory is even more cramped than ever before. This will help that a little bit by allowing arrows* and bolts to be used from a bauble slot.
Register a Quiver slot for ammo if Baubles Expanded is present. They can be put in a Ring slot instead (had to pick one) if just Baubles is present. Modifiers with effects like Moss and picking up ammo works while in a bauble slot.
Add info to the tooltip about the valid slot.
Clean up some unused and outdated logic in all the bow and ammo classes (improved switch statements, using EnumChatFormatting, removing unused variables, pattern variables, etc).
*~~Just TiCon arrows can be put in the slots for now, but bows can also use vanilla arrows. I will probably PR Hodgepodge to mixin vanilla ones, but …
=> Allow Ammo in Bauble Slots

dependencies.gradle, src/main/java/tconstruct/client/ArmorControls.java
While Minecraft allows configuring keybinds on mouse buttons, handling them needs explicit support in each mod. This additionally subscribes to `MouseInputEvent` to check if a button on there has been pressed).
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20978
=> Make mouse button keybinds more reliable

src/main/java/tconstruct/smeltery/blocks/SearedBlock.java
`Block#canConnectRedstone` which makes redstone powder traces automatically point towards components is more meant for redstone sources. To quote the MC wiki (as I'm too lazy to find the relevant source code):
> Redstone wire does not automatically configure itself to point toward _mechanism components_; the only exceptions are the back and side faces of pistons and sticky pistons in Bedrock Edition. If such a configuration is desired, the other neighbors of the redstone wire must be arranged to create it, i.e the redstone dust must be placed in a way that it would be pointed at the block’s location even if it were not there.
The wiki describes 3 basic redstone components: power, transmission, and mechanism components, of which the Faucet is the latter. And this is how the Faucet already …
=> Don't auto connect redstone traces to Faucets

src/main/java/tconstruct/library/weaponry/ProjectileWeapon.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/21149
Vanilla arrows are compatible and found by short and longbows code, but the code does not handle consuming them since vanilla arrows do not implement the custom IAmmo. This allowed for infinite ammo using one vanilla arrow, and duplicating them by picking them up.
=> fix: consume vanilla arrows instead of duplicating them

src/main/java/tconstruct/tools/logic/CraftingStationLogic.java
This would also happen if you had a double chest next to a trapped chest. If you opened the crafting station, you would see the contents of one half of the double chest + the trapped chest, instead of the contents of the entire double chest as expected.
=> Fix crafting station sometimes detecting a chest next to a trapped chest as a double chest
